# See https://pre-commit.com for more information
repos:
  - repo: local
    hooks:
      - id: task-dev-all
        name: task dev:all
        entry: task dev:all
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: task-operator-generate
        name: task generate
        entry: task operator:generate
        language: system
        pass_filenames: false
