version: '3'

includes:
  docker: tasks/docker.yaml
  k8s: tasks/k8s.yaml
  dev: tasks/dev.yaml
  chart: tasks/chart.yaml
  agent: code/agent/tasks/agent.yaml
  operator: code/operator/tasks/operator.yaml
  orchestrator: code/orchestrator/tasks/orchestrator.yaml

tasks:
  default:
   - task: deploy

  deploy:
    - task: dev:all
    - task: docker:build-all
    - task: k8s:create-ns
    - task: k8s:set-context
    - task: chart:install-dev
