version: "3"

tasks:
  install:
    - uv pip install -r environments/all-requirements.txt
    - pre-commit install

  format: ruff format
  lint: ruff check .
  lint-fix: ruff check . --fix
  type: ty check .
  commit-check: sh -c '[ "$(git rev-parse HEAD)" = "$(git rev-parse main)" ] && exit 0; cz check --rev-range main..HEAD'

  all:
    - task: install
    - task: format
    - task: lint-fix
    - task: type
    - task: commit-check