version: '3'

tasks:
  build-agent: docker build . -f ./code/agent/Dockerfile -t agentickube-agent

  build-operator: docker build . -f ./code/operator/Dockerfile -t agentickube-operator

  build-all:
    - task: build-agent
    - task: build-operator