version: '3'

tasks:
  run-orchestrator: watchmedo auto-restart --patterns "*.py" -d src/operator  -- kopf run src/operator/main.py --namespace=test --verbose

  create-ns: kubectl create namespace test || true

  set-context: kubectl config set-context --current --namespace=test || true

  init-ns: kubectl delete ag --all -n test && kubectl delete deployment --all -n test && kubectl delete pod --all -n test

  apply-crd: kubectl apply -f manifests/crd.yaml

  apply-folder: kubectl apply -f manifests/

  apply-all:
    - task: apply-crd
    - task: apply-folder