version: '3'

tasks:
  create-ns: kubectl create namespace agentickube-ns || true

  set-context: kubectl config set-context --current --namespace=agentickube-ns || true

  init-ns: 
    - kubectl delete agent --all -n agentickube-ns
    - kubectl delete orchestrator --all -n agentickube-ns
    - kubectl delete deployment --all -n agentickube-ns
    - kubectl delete replicaset --all -n agentickube-ns
    - kubectl delete pod --all -n agentickube-ns
    # - kubectl delete pvc --all -n agentickube-ns
    # - kubectl delete pv --all -n agentickube-ns
    - kubectl delete rolebinding --all -n agentickube-ns
    - kubectl delete role --all -n agentickube-ns
    - kubectl delete serviceaccount --all -n agentickube-ns
    - kubectl delete secret --all -n agentickube-ns
    - kubectl delete configmap --all -n agentickube-ns
    - kubectl delete service --all -n agentickube-ns
    - kubectl delete ingress --all -n agentickube-ns
    - kubectl delete cronjob --all -n agentickube-ns
    - kubectl delete job --all -n agentickube-ns

  apply-crd:
    - kubectl apply -f deploy/agent-crd.yaml
    - kubectl apply -f deploy/orchestrator-crd.yaml

  apply-operator: kubectl apply -f deploy/operator.yaml

  apply-rbac: kubectl apply -f deploy/example-rbac.yaml

  apply-manifests: kubectl apply -f manifests/

  apply-all:
    - task: apply-crd
    - task: apply-operator
    - task: apply-manifests
