{{- if .Values.agents }}
{{- range .Values.agents }}
apiVersion: ai.juliusharing.com/v1
kind: Agent
metadata:
  name: {{ .name | quote }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "1"
spec:
  {{- if .spec }}
  {{- toYaml .spec | nindent 2 }}
  {{- else }}
  image: {{ $.Values.agentImage.repository }}:{{ $.Values.agentImage.tag | default $.Chart.AppVersion | default "latest" }}
  imagePullPolicy: {{ $.Values.agentImage.pullPolicy }}
  {{- end }}
---
{{- end }}
{{- end }}
