{{- if .Values.orchestrators }}
{{- range .Values.orchestrators }}
apiVersion: ai.juliusharing.com/v1
kind: Orchestrator
metadata:
  name: {{ .name | quote }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "1"
spec:
  {{- if .spec }}
  {{- toYaml .spec | nindent 2 }}
  {{- else }}
  image: {{ $.Values.orchestratorImage.repository }}:{{ $.Values.orchestratorImage.tag | default $.Chart.AppVersion | default "latest" }}
  imagePullPolicy: {{ $.Values.orchestratorImage.pullPolicy }}
  agents: []
  {{- end }}
---
{{- end }}
{{- end }}
