{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agentickube-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: agentickube
{{- end }}
