{{- if .Values.agentickube.workspace.pvc.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.agentickube.workspace.pvc.name }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.agentickube.workspace.pvc.size }}
{{- end }}
