version: '3'

tasks:
  run: PYTHONPATH="code:code/agent/src" WORKSPACE_DIR="./code/agent/" SKILLS_CUSTOM_DIR="./code/agent/skills/custom" LLM_MODEL_NAME="qwen3:1.7b" LLM_BASE_URL="http://localhost:11434/v1" OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318 OTEL_SERVICE_NAME=agent-local python code/agent/src/main.py {{.CLI_ARGS}}
  
  run-bare: PYTHONPATH="code:code/agent/src" WORKSPACE_DIR="./code/agent/" SKILLS_BUILTIN_DIR="./code/agent/skills/builtin" SKILLS_CUSTOM_DIR="./code/agent/skills/custom" python code/agent/src/main.py {{.CLI_ARGS}}